---
apiVersion: v1
kind: Namespace
metadata:
  name: ray-training
---
apiVersion: ray.io/v1alpha1
kind: RayService
metadata:
  name: ray-training
  namespace: ray-training
spec:
  serviceUnhealthySecondThreshold: 600
  deploymentUnhealthySecondThreshold: 600
  serveConfig:
    importPath: ray-training:entrypoint
    runtimeEnv: |
      env_vars: {"MODEL_ID": "jinzishuai/ray-training"}
  rayClusterConfig:
    rayVersion: "2.6.0"
    headGroupSpec:
      rayStartParams:
        dashboard-host: "0.0.0.0"
      template:
        spec:
          containers:
            - name: ray-head
              image: jinzishuai/ray-train-dreambooth:latest
              resources:
                limits:
                  cpu: 2
                  memory: 16Gi
                  nvidia.com/gpu: 1
                requests:
                  cpu: 2
                  memory: 16Gi
                  nvidia.com/gpu: 1
              ports:
                - containerPort: 6379
                  name: gcs-server
                - containerPort: 8265
                  name: dashboard
                - containerPort: 10001
                  name: client
                - containerPort: 8000
                  name: serve
    workerGroupSpecs:
      - replicas: 1
        minReplicas: 1
        maxReplicas: 5
        rayStartParams: {}
        groupName: small-group
        template:
          spec:
            containers:
              - name: ray-worker
                image: jinzishuai/ray-train-dreambooth:latest
                lifecycle:
                  preStop:
                    exec:
                      command: ["/bin/sh", "-c", "ray stop"]
                resources:
                  limits:
                    cpu: "2"
                    memory: "16Gi"
                    nvidia.com/gpu: 1
                  requests:
                    cpu: "2"
                    memory: "16Gi"
                    nvidia.com/gpu: 1
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ray-training
  namespace: ray-training
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/$1"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          # Ray Dashboard
          - path: /ray-training/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: ray-training-head-svc
                port:
                  number: 8265
          # Ray Serve
          - path: /ray-training/serve/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: ray-training-head-svc
                port:
                  number: 8000
