apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: gpu-raycluster
  namespace: ray-gpu
spec:
  rayVersion: "2.8.1" # Ray version to use
  headGroupSpec:
    serviceType: ClusterIP
    rayStartParams:
      port: "6379"
      dashboard-host: "0.0.0.0"
    template:
      spec:
        containers:
          - name: ray-head
            image: jinzishuai/ray-train-dreambooth:2.8.1-py310-gpu
            ports:
              - containerPort: 6379
              - containerPort: 8265 # dashboard
            resources:
              requests:
                cpu: "2"
                memory: "13Gi"
                nvidia.com/gpu: "1" # Request one NVIDIA GPU
              limits:
                cpu: "2"
                memory: "15Gi"
                nvidia.com/gpu: "1" # Limit one NVIDIA GPU
            volumeMounts:
              - name: persistent-storage
                mountPath: /data
        volumes:
          - name: persistent-storage
            persistentVolumeClaim:
              claimName: efs-claim
  workerGroupSpecs:
    - groupName: worker-group
      replicas: 0
      minReplicas: 0
      maxReplicas: 3
      rayStartParams: {}
      template:
        spec:
          containers:
            - name: ray-worker
              image: jinzishuai/ray-train-dreambooth:2.8.1-py310-gpu
              resources:
                requests:
                  cpu: "1"
                  memory: "10Gi"
                  nvidia.com/gpu: "1" # Request one NVIDIA GPU
                limits:
                  cpu: "2"
                  memory: "15Gi"
                  nvidia.com/gpu: "1" # Limit one NVIDIA GPU
              volumeMounts:
                - name: persistent-storage
                  mountPath: /data
          volumes:
            - name: persistent-storage
              persistentVolumeClaim:
                claimName: efs-claim
